const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./app/routers/ciclope.changer.routers.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "Ciclope Changer",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8000",
    basePath: "/api/action",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Action",
            "description": "Endpoint to change an FQDN associated with a VPN."
        }
    ],
    definitions: {
        Action: {
            vpnName: 'Conductor',
            recordId: '998788de-f118-11ec-a7e6-1680a1ffe1fd',
            vpnAlternate: 'vpn-pico-a.partner.example.com.br',
            subDomain: 'partner.example.com.br',
            requester: 'conductor-app',
            description: 'This a request test.'
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js');
})