apiVersion: v1
data:
  CHATOPS_URL: http://ciclope-chatops.ciclope:7073/app/v1/send
  CDC_HOST: pdc.furycloud.io
  DOMAIN: mercadplibre.io
  TTL: "null"
  RECORD_TYPE: CNAME
  TYPE: DEVICE
  PROVIDER_NAME: Amazon-Fury_Core
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ciclope-changer-config
  namespace: ciclope