apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: changer
  name: changer
  namespace: ciclope
spec:
  replicas: 2
  selector:
    matchLabels:
      app: changer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: changer
    spec:
      volumes:
        - name: changer-config
          configMap:
              name: changer-config
      containers:
      - name: changer
        image: 149815134901.dkr.ecr.us-east-1.amazonaws.com/k8s-ciclope-changer-build-ecr:ciclope-changer-0.1.0
        imagePullPolicy: Always
        volumeMounts:
          - name: .env
            mountPath: "/opt/app"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m" 
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/health-check
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60







