apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ciclope-changer
  name: ciclope-changer
  namespace: ciclope
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ciclope-changer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ciclope-changer
    spec:
      containers:
      - name: ciclope-changer
        image: 149815134901.dkr.ecr.us-east-1.amazonaws.com/k8s-ciclope-changer-build-ecr:ciclope-changer-1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m" 
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60
        env:
          - name: CHATOPS_URL
            valueFrom:
              configMapKeyRef:
                name: ciclope-changer-config
                key: CHATOPS_URL