apiVersion: v1
data:
  CHATOPS_URL: http://ciclope-chatops.ciclope:7073/app/v1/send
  CDC_HOST: pdc.furycloud.io
  DOMAIN: mercadolibre.io
  CONDUCTOR_RECORD_TTL: "60"
  CONDUCTOR_RECORD_TYPE: "A"
  CONDUCTOR_DESCRIPTION: "Conductor"
  FQDN_CONDUCTOR: conductor-stg-in-cloudexchange.mercadolibre.io
  SCOPE: "stg"
  HOSTED_ZONE_ID: "Z1QC71E4D01CPS"
  CONDUCTOR_PROVIDER_NAME: Amazon-Fury_Core
  CONDUCTOR_RECORD_OFF_TRAFFIC: "0"
  CONDUCTOR_RECORD_ON_TRAFFIC: "255"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: changer-config
  namespace: ciclope
