name: CI

on:
  pull_request:
    branches: [ "develop" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: App start
        env:
          CHATOPS_URL: ${{ secrets.CHATOPS_URL }}
          CDC_HOST: ${{ secrets.CDC_HOST }}
          DOMAIN: ${{ secrets.DOMAIN }}
          CONDUCTOR_RECORD_TTL: ${{ secrets.CONDUCTOR_RECORD_TTL }}
          CONDUCTOR_RECORD_TYPE: ${{ secrets.CONDUCTOR_RECORD_TYPE }}
          CONDUCTOR_DESCRIPTION: ${{ secrets.CONDUCTOR_DESCRIPTION }}
          FQDN_CONDUCTOR: ${{ secrets.FQDN_CONDUCTOR }}
          SCOPE: ${{ secrets.SCOPE }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CONDUCTOR_PROVIDER_NAME: ${{ secrets.CONDUCTOR_PROVIDER_NAME }}
          CONDUCTOR_RECORD_OFF_TRAFFIC: ${{ secrets.CONDUCTOR_RECORD_OFF_TRAFFIC }}
          CONDUCTOR_RECORD_ON_TRAFFIC: ${{ secrets.CONDUCTOR_RECORD_ON_TRAFFIC }}
        run: |
          bash ${GITHUB_WORKSPACE}/start.sh &
      - name: Run test
        run: pytest
